### ISSUE TITLE
几乎完美，非常感谢。不过可以更新一下VoodooPS2Controller.kext

### ISSUE THREAD

**Issue by icewindq** [SteVeNRK/Hackintosh-Clover-EFI-ThinkPad-E430#1]
非常感谢，用了你的Clover，运行很正常。不过有几个小问题。

1. 触摸板驱动不是太正常，比如三指切换桌面。我更新了下VoodooPS2Controller.kext到2.1.5版本，几乎所有三指四指手势都跟原生差不多。
2. 想请教一下你的电池显示怎么修复的。我之前一直不能正常显示，一直都是0%，你说一下你解决的思路吗？
再次感谢。

**Comment by SteVeNRK** [comment]
我没触摸板 所以没法测试 电池用 masl 那工具 改DSDT有个叫 派奇 的源 他的源里有脚本





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: icewindq <notifications@github.com&gt;
发送时间: 2020年7月12日 18:04
收件人: SteVeNRK/Hackintosh-Clover-EFI-ThinkPad-E430 <Hackintosh-Clover-EFI-ThinkPad-E430@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[SteVeNRK/Hackintosh-Clover-EFI-ThinkPad-E430] 几乎完美，非常感谢。不过可以更新一下VoodooPS2Controller.kext (#1)





 
非常感谢，用了你的Clover，运行很正常。不过有几个小问题。
  
触摸板驱动不是太正常，比如三指切换桌面。我更新了下VoodooPS2Controller.kext到2.1.5版本，几乎所有三指四指手势都跟原生差不多。 

想请教一下你的电池显示怎么修复的。我之前一直不能正常显示，一直都是0%，你说一下你解决的思路吗？
 再次感谢。

**Comment by SteVeNRK** [comment]
https://github.com/SteVeNRK/Hackintosh-OpenCore-EFI-ThinkPad-E430




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SteVeNRK/Hackintosh-Clover-EFI-ThinkPad-E430"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月12日(星期天) 晚上6:04
收件人:&nbsp;"SteVeNRK/Hackintosh-Clover-EFI-ThinkPad-E430"<Hackintosh-Clover-EFI-ThinkPad-E430@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[SteVeNRK/Hackintosh-Clover-EFI-ThinkPad-E430] 几乎完美，非常感谢。不过可以更新一下VoodooPS2Controller.kext (#1)





 
非常感谢，用了你的Clover，运行很正常。不过有几个小问题。
  
触摸板驱动不是太正常，比如三指切换桌面。我更新了下VoodooPS2Controller.kext到2.1.5版本，几乎所有三指四指手势都跟原生差不多。
 
想请教一下你的电池显示怎么修复的。我之前一直不能正常显示，一直都是0%，你说一下你解决的思路吗？
 再次感谢。

**Comment by SteVeNRK** [comment]
https://github.com/SteVeNRK/Hackintosh-OpenCore-EFI-ThinkPad-E430


我更新了一下，添加回了&nbsp;ACPIBatteryManager.kext 驱动，这个是 OpenCore 的版本，Clover 版本里本来就有这个驱动，添加回这个驱动后就可以解决之前有电量显示后来为啥又没电量显示的问题了。







MaciASL app 自己添加一个&nbsp;派奇 源&nbsp;http://raw.github.com/Yuki-Judai/dxxs-DSDT-Patch/master


他的 GitHub 地址：https://github.com/Yuki-Judai/dxxs-DSDT-Patch


直接给 DSDT 打补丁就可以解决电池电量的问题了。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SteVeNRK/Hackintosh-Clover-EFI-ThinkPad-E430"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月12日(星期天) 晚上6:04
收件人:&nbsp;"SteVeNRK/Hackintosh-Clover-EFI-ThinkPad-E430"<Hackintosh-Clover-EFI-ThinkPad-E430@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[SteVeNRK/Hackintosh-Clover-EFI-ThinkPad-E430] 几乎完美，非常感谢。不过可以更新一下VoodooPS2Controller.kext (#1)





 
非常感谢，用了你的Clover，运行很正常。不过有几个小问题。
  
触摸板驱动不是太正常，比如三指切换桌面。我更新了下VoodooPS2Controller.kext到2.1.5版本，几乎所有三指四指手势都跟原生差不多。
 
想请教一下你的电池显示怎么修复的。我之前一直不能正常显示，一直都是0%，你说一下你解决的思路吗？
 再次感谢。

**Comment by icewindq** [comment]
谢谢你的回答
